spring:
  application:
    name: eureka-server
  security:
    basic:
      enable: true
    user:
      name: mseurekauser
      password: kmsrauerseue

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false













